Style/37 responsive fact page tf
chingu-voyages/v42-toucans-team-03 pull request #40
Opened 2023-01-23 23:11 UTC by terrifricker

2023-01-24 16:42 UTC, QuangLyHo requested changes
Looks much better than before.

The categories page still needs some work on smaller screens. some parts still get cut off

2023-01-24 19:20 UTC, terrifricker commented
Yes!  These are only changes for the facts page.

2023-01-25 18:52 UTC, terrifricker commented
@QuangLyHo @alekzandriia I've pulled a different branch for changes on the Category page.  Please see if these changes just for the Facts page can be approved.

2023-01-25 22:41 UTC, alekzandriia approved these changes

2023-01-26 16:23 UTC, QuangLyHo approved these changes

2023-01-26 16:23 UTC, merged